#######################################
# DbWin messages
#######################################

SECTIONPREFIXOFF					# Nomi delle variabili semplici

[IT] = ON
[EN] = OFF

[IT]
# Messaggi
STR MsgClosing =			"Uscire dal programma ?"
STR MsgDisconnecting =		"Disconnettersi ?"
STR MsgDisconnected =		"Disconnesso"
STR MsgConnected =			"Connesso"
STR MsgNotConnected =		"Non connesso"

# Menù e titoli
STR MnuClosing		=		"Uscita"
STR MnuDisconnecting =		"Disconnessione"
STR MnuStatus		=		"Stato della connessione"

STR MnuConnecting	=		"Connessione"
STR MnuConnect		=		"Connetti"
STR MnuDisconnect	=		"Disconnetti"
STR MnuParameters	=		"Parametri"
STR MnuStatus		=		"Stato"
STR MnuConnString	=		"Stringa di connessione"
STR MnuSchema		=		"Schema"
STR MnuProcedures	=		"Procedure"
STR MnuFunctions	=		"Funzioni"
STR MnuExit			=		"Esci"
STR MnuNfo			=		"Informazioni"
STR MnuDetails		=		"Dettagli"
[.]


[EN]
# Messages
STR MsgClosing =			"Exit program ?"
STR MsgDisconnecting =		"Disconnect ?"
STR MsgDisconnected =		"Disconnected"
STR MsgConnected =			"Connected"
STR MsgNotConnected =		"Not connected"

# Menus and titles
STR MnuClosing =			"Closing"
STR MnuDisconnecting =		"Disconnection"
STR MnuStatus =				"Connection status"
STR MnuConnecting	=		"Connection"
STR MnuConnect		=		"Connect"
STR MnuDisconnect	=		"Disconnect"
STR MnuParameters	=		"Parameters"
STR MnuStatus		=		"Status"
STR MnuConnString	=		"Connection string"
STR MnuSchema		=		"Schema"
STR MnuProcedures	=		"Procedures"
STR MnuFunctions	=		"Functions"
STR MnuExit			=		"Exit"
STR MnuNfo			=		"Info"
STR MnuDetails		=		"Details"
[.]
